#!/usr/bin/env python3
"""One-shot generator for config/src/i18n/zh_cn.rs (fork).

Takes the (english_key, zh_cn) pairs below, byte-sorts by key and emits
the ZH_CN static slice so the `zh_table_sorted_unique` test can never
drift.  Run manually when adding entries; the output is committed.

    python3 scripts/gen_zh_table.py > config/src/i18n/zh_cn.rs
"""

PAIRS = [
    # ---- command palette: static briefs ----
    ("Paste primary selection", "粘贴主选区"),
    ("Copy to primary selection", "复制到主选区"),
    ("Copy to clipboard", "复制到剪贴板"),
    ("Copy to clipboard and primary selection", "复制到剪贴板和主选区"),
    ("Paste from clipboard", "从剪贴板粘贴"),
    ("Toggle full screen mode", "切换全屏模式"),
    ("Toggle always on Top", "切换窗口置顶"),
    ("Toggle always on Bottom", "切换窗口置底"),
    ("Always on Top", "窗口置顶"),
    ("Normal", "普通层级"),
    ("Always on Bottom", "窗口置底"),
    ("Hide/Minimize Window", "隐藏/最小化窗口"),
    ("Show/Restore Window", "显示/恢复窗口"),
    ("Hide Application", "隐藏应用"),
    ("New Window", "新建窗口"),
    ("Clear scrollback", "清除回滚缓冲"),
    ("Clear the scrollback and viewport", "清除回滚缓冲与可视区"),
    ("Search pane output", "搜索窗格输出"),
    ("Show debug overlay", "显示调试浮层"),
    ("Prompt the user to choose from a list", "弹出列表让用户选择"),
    ("Prompt the user for confirmation", "弹出确认对话框"),
    ("Prompt the user for a line of text", "弹出单行文本输入"),
    ("Enter QuickSelect mode", "进入快速选择模式"),
    ("Enter Emoji / Character selection mode", "进入 Emoji / 字符选择模式"),
    ("Enter Pane selection mode", "进入窗格选择模式"),
    ("Swap a pane with the active pane", "交换窗格与活动窗格"),
    ("Swap a pane with the active pane, keeping focus", "交换窗格与活动窗格（保持焦点）"),
    ("Move a pane into its own tab", "将窗格移到独立标签页"),
    ("Move a pane into its own window", "将窗格移到独立窗口"),
    ("Decrease font size", "减小字号"),
    ("Increase font size", "增大字号"),
    ("Reset font size", "重置字号"),
    ("Reset the window and font size", "重置窗口与字号"),
    ("New Tab", "新建标签页"),
    ("New Tab (Default Domain)", "新建标签页（默认域）"),
    ("Activate right-most tab", "激活最右侧标签页"),
    ("Close current Tab", "关闭当前标签页"),
    ("Close current Pane", "关闭当前窗格"),
    ("Activate the preceeding window", "激活上一个窗口"),
    ("Activate the next window", "激活下一个窗口"),
    ("Activate the tab to the left", "激活左侧标签页"),
    ("Activate the tab to the right", "激活右侧标签页"),
    ("Activate the tab to the left (no wrapping)", "激活左侧标签页（不循环）"),
    ("Activate the tab to the right (no wrapping)", "激活右侧标签页（不循环）"),
    ("Reload configuration", "重载配置"),
    ("Quit WezTerm", "退出 WezTerm"),
    ("Move tab one place to the left", "标签页左移一位"),
    ("Move tab one place to the right", "标签页右移一位"),
    ("Scroll Up One Page", "向上滚动一页"),
    ("Scroll Down One Page", "向下滚动一页"),
    (
        "Scrolls based on the mouse wheel position in the current mouse event",
        "按当前鼠标事件中的滚轮增量滚动",
    ),
    ("Scroll to the bottom", "滚动到底部"),
    ("Scroll to the top", "滚动到顶部"),
    ("Activate Copy Mode", "进入复制模式"),
    ("Split Vertically (Top/Bottom)", "垂直分屏（上/下）"),
    ("Split Horizontally (Left/Right)", "水平分屏（左/右）"),
    ("Activate Pane Left", "激活左侧窗格"),
    ("Activate Pane Right", "激活右侧窗格"),
    ("Activate Pane Up", "激活上方窗格"),
    ("Activate Pane Down", "激活下方窗格"),
    ("Toggle Pane Zoom", "切换窗格缩放"),
    ("Activate the last active tab", "激活最近活动的标签页"),
    ("Clear the key table stack", "清空键表栈"),
    ("Open link at mouse cursor", "打开鼠标处的链接"),
    ("Show the launcher", "显示启动器"),
    ("Navigate tabs", "浏览标签页"),
    ("Detach the domain of the active pane", "脱离活动窗格所在的域"),
    ("Detach the default domain", "脱离默认域"),
    ("Documentation", "文档"),
    ("Discuss on GitHub", "到 GitHub 讨论"),
    ("Search or report issue on GitHub", "在 GitHub 搜索或报告问题"),
    ("Does nothing", "无操作"),
    ("Clears the selection in the current pane", "清除当前窗格的选区"),
    ("Pop the current key table", "弹出当前键表"),
    ("Reset the terminal emulation state in the current pane", "重置当前窗格的终端仿真状态"),
    ("Activate Command Palette", "打开命令面板"),
    ("Shows the command palette modal", "显示命令面板浮层"),
    ("Open Settings", "打开设置"),
    ("Shows the settings overlay", "显示设置浮层"),
    ("Show Main Menu", "打开主菜单"),
    ("Shows the main menu overlay", "显示主菜单浮层"),
    ("Show Keybindings", "查看快捷键"),
    ("Shows the keybinding cheat sheet overlay", "显示快捷键速查浮层"),
    ("Keybindings", "快捷键"),
    ("↑↓ scroll  Esc close", "↑↓ 滚动  Esc 关闭"),
    # ---- CLI 帮助（clap 运行时本地化）----
    ("Wez's Terminal Emulator", "Wez 的终端模拟器"),
    ("Print help", "打印帮助"),
    ("Start the GUI, optionally running an alternative program [aliases: -e]", "启动 GUI，可选地运行其它程序 [别名: -e]"),
    ("Wez's Terminal Emulator\nhttp://github.com/wezterm/wezterm", "Wez 的终端模拟器\nhttp://github.com/wezterm/wezterm"),
    ("Print help (see a summary with '-h')", "打印帮助（用 '-h' 查看摘要）"),
    ("Print version", "打印版本"),
    ("Print this message or the help of the given subcommand(s)", "打印本消息或指定子命令的帮助"),
    ("Skip loading wezterm.lua", "跳过加载 wezterm.lua"),
    (
        "Specify the configuration file to use, overrides the normal configuration file resolution",
        "指定要使用的配置文件，覆盖常规的配置文件查找顺序",
    ),
    ("Override specific configuration values", "覆盖指定的配置项"),
    # 子命令 about
    ("Start the GUI, optionally running an alternative program", "启动 GUI，可选地运行其它程序"),
    ("Establish an ssh session", "建立 ssh 会话"),
    ("Open a serial port", "打开串口"),
    ("Connect to wezterm multiplexer", "连接到 wezterm 多路复用器"),
    ("Display information about fonts", "显示字体信息"),
    ("Show key assignments", "显示键位分配"),
    ("Interact with experimental mux server", "与实验性 mux 服务端交互"),
    ("Output an image to the terminal", "在终端中输出图片"),
    (
        "Advise the terminal of the current working directory by emitting an OSC 7 escape sequence",
        "通过发送 OSC 7 转义序列告知终端当前工作目录",
    ),
    ("Record a terminal session as an asciicast", "将终端会话录制为 asciicast"),
    ("Replay an asciicast terminal session", "回放 asciicast 终端会话"),
    ("Generate shell completion information", "生成 shell 补全信息"),
    ("list windows, tabs and panes", "列出窗口、标签页和窗格"),
    ("list clients", "列出客户端"),
    ("start rpc proxy pipe", "启动 RPC 代理管道"),
    ("obtain tls credentials", "获取 TLS 凭据"),
    ("split the current pane.", "拆分当前窗格。"),
    ("Move a pane into a new tab", "将窗格移入新标签页"),
    ("Activate (focus) a pane", "激活（聚焦）窗格"),
    ("Activate an adjacent pane in the specified direction", "激活指定方向上的相邻窗格"),
    ("Determine the adjacent pane in the specified direction", "确定指定方向上的相邻窗格"),
    ("Adjust the size of a pane directionally", "按方向调整窗格大小"),
    ("Activate a tab", "激活标签页"),
    ("Change the title of a tab", "修改标签页标题"),
    ("Change the title of a window", "修改窗口标题"),
    ("Rename a workspace", "重命名工作区"),
    ("Send text to a pane as though it were pasted. If bracketed paste mode is enabled in the pane, then the text will be sent as a bracketed paste", "向窗格发送文本，如同粘贴。若窗格启用了括号粘贴模式，文本将按括号粘贴发送"),
    ("Retrieves the textual content of a pane and output it to stdout", "获取窗格的文本内容并输出到标准输出"),
    ("Kill a pane", "关闭窗格"),
    ("Spawn a command into a new window or tab", "在新窗口或新标签页中启动命令"),
    ("Zoom, unzoom, or toggle zoom state", "缩放、取消缩放或切换缩放状态"),
    # 常用参数 help
    (
        "Instead of executing your shell, run PROG. For example: `wezterm start -- bash -l` will spawn bash as if it were a login shell",
        "不执行你的 shell，而是运行 PROG。例如：`wezterm start -- bash -l` 会以登录 shell 的方式启动 bash",
    ),
    (
        "Instead of executing your shell, run PROG. For example: `wezterm ssh user@host -- bash -l` will spawn bash as if it were a login shell",
        "不执行你的 shell，而是运行 PROG。例如：`wezterm ssh user@host -- bash -l` 会以登录 shell 的方式启动 bash",
    ),
    (
        "Instead, always start the GUI in this invocation of wezterm so that you can wait for the command to complete by waiting for this wezterm process to finish",
        "总是在本次 wezterm 调用中直接启动 GUI，这样等待本进程结束即可等待命令完成",
    ),
    ("If true, do not connect to domains marked as connect_automatically in your wezterm configuration file", "为 true 时不自动连接配置文件中标记为 connect_automatically 的域"),
    (
        "Override the default windowing system class. The default is \"org.wezfurlong.wezterm\". Under X11 and Windows this changes the window class. Under Wayland this changes the app_id. This changes the class for all windows spawned by this instance of wezterm, including error, update and ssh authentication dialogs",
        "覆盖窗口系统默认的 class。默认为 \"org.wezfurlong.wezterm\"。X11 与 Windows 下修改窗口 class，Wayland 下修改 app_id。此设置影响该 wezterm 实例派生的所有窗口，包括错误、更新与 ssh 认证对话框",
    ),
    ("Override the default workspace with the provided name. The default is \"default\"", "用给定名称覆盖默认工作区。默认名为 \"default\""),
    (
        "When connecting to a gui instance, if you started the gui with `--class SOMETHING`, you should also pass that same value here in order for the client to find the correct gui instance",
        "连接 GUI 实例时，若 GUI 以 `--class SOMETHING` 启动，客户端也需传入相同值才能找到正确的 GUI 实例",
    ),
    (
        "When used with --domain, if the domain already has running panes, wezterm will simply attach and will NOT spawn the specified PROG. If you omit --attach when using --domain, wezterm will attach AND then spawn PROG",
        "与 --domain 同用时，若域中已有运行中的窗格，wezterm 将仅附加而不会启动指定的 PROG；若省略 --attach，wezterm 会先附加再启动 PROG",
    ),
    ("Prefer connecting to a background mux server. The default is to prefer connecting to a running wezterm gui instance", "优先连接后台 mux 服务端。默认优先连接运行中的 wezterm GUI 实例"),
    (
        "Specifies the remote system using the form: `[username@]host[:port]`. If `username@` is omitted, then your local $USER is used instead. If `:port` is omitted, then the standard ssh port (22) is used instead",
        "以 `[用户名@]主机[:端口]` 形式指定远程系统。省略 `用户名@` 时使用本地 $USER；省略 `:端口` 时使用标准 ssh 端口（22）",
    ),
    (
        "Instead of executing your shell, run PROG. For example: `wezterm start -- bash -l` will spawn bash as if it were a login shell.",
        "不执行你的 shell，而是运行 PROG。例如：`wezterm start -- bash -l` 会以登录 shell 的方式启动 bash。",
    ),
    (
        "Override specific SSH configuration options. `wezterm ssh` is able to parse some (but not all!) options from your `~/.ssh/config` and `/etc/ssh/ssh_config` files. This command line switch allows you to override or otherwise specify ssh_config style options.",
        "覆盖指定的 SSH 配置项。`wezterm ssh` 能解析 `~/.ssh/config` 与 `/etc/ssh/ssh_config` 中的部分（不是全部！）选项，此开关允许你覆盖或补充 ssh_config 风格的选项。",
    ),
    ("Enable verbose ssh protocol tracing. The trace information is printed to the stderr stream of the process", "启用 ssh 协议详细跟踪，跟踪信息打印到进程的标准错误流"),
    (
        "Specifies the serial device name. On Windows systems this can be a name like `COM0`. On posix systems this will be something like `/dev/ttyUSB0`",
        "指定串口设备名。Windows 系统上形如 `COM0`，POSIX 系统上形如 `/dev/ttyUSB0`",
    ),
    ("Set the baud rate.  The default is 9600 baud", "设置波特率。默认 9600"),
    (
        "Name of the multiplexer domain section from the configuration to which you'd like to connect",
        "要连接的配置文件中多路复用域（domain）小节的名称",
    ),
    (
        "Name of the multiplexer domain section from the configuration to which you'd like to connect. If omitted, the default domain will be used",
        "要连接的配置文件中多路复用域（domain）小节的名称。省略时使用默认域",
    ),
    ("Whether to list all fonts available to the system", "是否列出系统可用的全部字体"),
    ("Explain which fonts are used to render the supplied text string", "说明用哪些字体渲染给定的文本字符串"),
    ("Explain which fonts are used to render the specified unicode code point sequence. Code points are comma separated hex values", "说明用哪些字体渲染指定的 Unicode 码点序列。码点为逗号分隔的十六进制值"),
    ("Show rasterized glyphs for the text in --text or --codepoints using ascii blocks", "用 ASCII 字符块显示 --text 或 --codepoints 文本的光栅化字形"),
    ("In lua mode, show only the named key table", "lua 模式下仅显示指定名称的键表"),
    ("Show the keys as lua config statements", "以 lua 配置语句形式显示键位"),
    (
        "Start in the specified directory, instead of the default_cwd defined by your wezterm configuration",
        "在指定目录中启动，而非使用配置中的 default_cwd",
    ),
    ("Start prog instead of the default_prog defined by your wezterm configuration", "启动指定程序，而非配置中的 default_prog"),
    ("Specify the current working directory for the initially spawned program", "为初始启动的程序指定工作目录"),
    ("The directory to specify. If omitted, will use the current directory of the process itself", "要指定的目录。省略时使用进程自身的当前目录"),
    ("The hostname to use in the constructed file:// URL. If omitted, the system hostname will be used", "构造 file:// URL 时使用的主机名。省略时使用系统主机名"),
    ("The name of the image file to be displayed. If omitted, will attempt to read it from stdin", "要显示的图片文件名。省略时尝试从标准输入读取"),
    ("Wait for enter/escape/ctrl-c/ctrl-d to be pressed after displaying the image", "显示图片后等待按回车/Esc/Ctrl-C/Ctrl-D"),
    (
        "Do not move the cursor after displaying the image. Note that when used like this from the shell, there is a very high chance that shell prompt will overwrite the image; you may wish to also use `--hold` in that case",
        "显示图片后不移动光标。注意：在 shell 中这样使用时，shell 提示符极可能覆盖图片；此时可考虑同时使用 `--hold`",
    ),
    (
        "Set the cursor position prior to displaying the image. The default is to use the current cursor position. Coordinates are expressed in cells with 0,0 being the top left cell position",
        "显示图片前设置光标位置。默认使用当前光标位置。坐标以单元格表示，(0,0) 为左上角",
    ),
    ("Do not respect the aspect ratio.  The default is to respect the aspect ratio", "不保持宽高比。默认保持宽高比"),
    (
        "Set the maximum number of pixels per image frame. Images will be scaled down so that they do not exceed this size, unless `--no-resample` is also used. The default value matches the limit set by wezterm. Note that resampling the image here will reduce any animated images to a single frame",
        "设置每个图片帧的最大像素数。除非同时使用 `--no-resample`，超过该尺寸的图片会被缩小。默认值与 wezterm 内置限制一致。注意：此处重采样会把动图降为单帧",
    ),
    (
        "Do not resample images whose frames are larger than the max-pixels value. Note that this will typically result in the image refusing to display in wezterm",
        "不重采样超过 max-pixels 的图片帧。注意这通常会导致图片拒绝在 wezterm 中显示",
    ),
    ("Save asciicast to the specified file, instead of using a random file name in the temp directory", "将 asciicast 保存到指定文件，而非临时目录中的随机文件名"),
    ("Don't replay, just show the explanation", "不回放，仅显示说明"),
    ("Just emit raw escape sequences all at once, with no timing information", "一次性输出原始转义序列，不带时间信息"),
    ("Explain what is being sent/received", "说明发送/接收的内容"),
    # cli 子命令参数
    ("Controls the output format. \"table\" and \"json\" are possible formats", "控制输出格式。可用 \"table\" 与 \"json\""),
    ("Create tab in a new window, rather than the window currently containing the pane", "在新窗口中创建标签页，而非窗格当前所在的窗口"),
    ("When spawning into an existing GUI instance, spawn a new tab into the active window rather than spawn a new window", "注入既有 GUI 实例时，在活动窗口中新建标签页而非新窗口"),
    (
        "Specify the current pane. The default is to use the current pane based on the environment variable WEZTERM_PANE",
        "指定当前窗格。默认依据环境变量 WEZTERM_PANE 确定当前窗格",
    ),
    (
        "Specify the current pane. The default is to use the current pane based on the environment variable WEZTERM_PANE.",
        "指定当前窗格。默认依据环境变量 WEZTERM_PANE 确定当前窗格。",
    ),
    (
        "Specify the current pane. The default is to use the current pane based on the environment variable WEZTERM_PANE. The pane is used to determine the current domain and window",
        "指定当前窗格。默认依据环境变量 WEZTERM_PANE 确定当前窗格。该窗格用于确定当前域与窗口",
    ),
    (
        "Specify the target pane. The default is to use the current pane based on the environment variable WEZTERM_PANE",
        "指定目标窗格。默认依据环境变量 WEZTERM_PANE 确定当前窗格",
    ),
    (
        "Specify the pane that should be split. The default is to use the current pane based on the environment variable WEZTERM_PANE",
        "指定要拆分的窗格。默认依据环境变量 WEZTERM_PANE 确定当前窗格",
    ),
    (
        "Specify the pane that should be moved. The default is to use the current pane based on the environment variable WEZTERM_PANE",
        "指定要移动的窗格。默认依据环境变量 WEZTERM_PANE 确定当前窗格",
    ),
    ("Outputs the pane-id for the newly created pane on success", "成功时输出新建窗格的 pane-id"),
    ("Split vertically, with the new pane on the top", "垂直拆分，新窗格在上方"),
    ("Split vertically, with the new pane on the bottom", "垂直拆分，新窗格在下方"),
    ("Split horizontally, with the new pane on the left", "水平拆分，新窗格在左侧"),
    ("Split horizontally, with the new pane on the right", "水平拆分，新窗格在右侧"),
    ("Equivalent to `--right`. If neither this nor any other direction is specified, the default is equivalent to `--bottom`", "等价于 `--right`。若未指定任何方向，默认等价于 `--bottom`"),
    ("Rather than splitting the active pane, split the entire window", "拆分整个窗口而非仅活动窗格"),
    ("Instead of spawning a new command, move the specified pane into the newly created split", "不启动新命令，而是把指定窗格移入新创建的拆分"),
    ("Specify the number of cells that the new split should have, expressed as a percentage of the available space", "以可用空间的百分比指定新拆分的单元格数"),
    ("The number of cells that the new split should have. If omitted, 50% of the available space is used", "新拆分应有的单元格数。省略时使用可用空间的 50%"),
    ("You may also use an integer value `N` to specify the number of cells, or `Npx` to specify the number of pixels, or `N%` to size relative to the terminal width", "也可用整数 `N` 指定单元格数、`Npx` 指定像素数、或 `N%` 按终端宽度比例设置"),
    ("You may also use an integer value `N` to specify the number of cells, or `Npx` to specify the number of pixels, or `N%` to size relative to the terminal height", "也可用整数 `N` 指定单元格数、`Npx` 指定像素数、或 `N%` 按终端高度比例设置"),
    ("Spawn into a new window, rather than a new tab", "在新窗口而非新标签页中启动"),
    (
        "If creating a new window, override the default workspace name with the provided name.  The default name is \"default\"",
        "创建新窗口时用给定名称覆盖默认工作区名。默认名为 \"default\"",
    ),
    (
        "When creating a new window, override the default workspace name with the provided name.  The default name is \"default\". Requires `--new-window`",
        "创建新窗口时用给定名称覆盖默认工作区名。默认名为 \"default\"。需要 `--new-window`",
    ),
    (
        "Specify the window into which the new tab will be created. If omitted, the window associated with the current pane is used",
        "指定在新标签页创建到哪个窗口。省略时使用当前窗格所属窗口",
    ),
    (
        "Specify the window into which to spawn a tab. If omitted, the window associated with the current pane is used. Cannot be used with `--workspace` or `--new-window`",
        "指定标签页启动到哪个窗口。省略时使用当前窗格所属窗口。不能与 `--workspace` 或 `--new-window` 同用",
    ),
    ("Specify the target window by its id", "按 id 指定目标窗口"),
    (
        "Specify the target tab by its index within the window that holds the current pane. Indices are 0-based, with 0 being the left-most tab. Negative numbers can be used to reference the right-most tab, so -1 is the right-most tab, -2 is the penultimate tab and so on",
        "按当前窗格所在窗口内的索引指定目标标签页。索引从 0 开始，0 为最左侧标签页。可用负数从右侧引用：-1 为最右，-2 为倒数第二，依此类推",
    ),
    (
        "Specify the target tab by its relative offset. -1 selects the tab to the left. -2 two tabs to the left. 1 is one tab to the right and so on.",
        "按相对偏移指定目标标签页。-1 为左侧相邻，-2 为左移两个，1 为右侧相邻，依此类推。",
    ),
    ("The new title for the tab", "标签页的新标题"),
    ("The new title for the window", "窗口的新标题"),
    ("The pane is used to figure out which tab should be renamed.", "依据该窗格确定要重命名的标签页。"),
    ("The pane is used to figure out which window should be renamed.", "依据该窗格确定要重命名的窗口。"),
    ("The pane is used to figure out which window contains appropriate tabs", "依据该窗格确定包含相关标签页的窗口"),
    ("The pane is used to figure out which workspace should be renamed.", "依据该窗格确定要重命名的工作区。"),
    ("The new name for the workspace", "工作区的新名称"),
    ("Specify the workspace to rename", "指定要重命名的工作区"),
    ("Send the text directly, rather than as a bracketed paste", "直接发送文本，而非按括号粘贴发送"),
    ("The starting line number. 0 is the first line of terminal screen. Negative numbers proceed backwards into the scrollback. The default value is unspecified is 0, the first line of the terminal screen", "起始行号。0 为终端屏幕第一行，负数向回滚缓冲回溯。未指定时默认为 0（终端屏幕第一行）"),
    ("The ending line number. 0 is the first line of terminal screen. Negative numbers proceed backwards into the scrollback. The default value if unspecified is the bottom of the the terminal screen", "结束行号。0 为终端屏幕第一行，负数向回滚缓冲回溯。未指定时默认为终端屏幕底部"),
    ("Include escape sequences that color and style the text. If omitted, unattributed text will be returned", "包含着色与样式转义序列。省略时返回不带属性的文字"),
    ("The direction to consider", "要考虑的方向"),
    ("Specify the number of cells to resize by, defaults to 1", "指定调整的单元格数，默认为 1"),
    ("Prints the pane id in that direction, or nothing if there is no pane in that direction.", "打印该方向上的窗格 id；该方向没有窗格则不输出。"),
    ("Toggles the zoom state of the pane", "切换窗格的缩放状态"),
    ("Zooms the pane", "缩放窗格"),
    ("Unzooms the pane if it was zoomed", "若窗格处于缩放状态则取消缩放"),
    ("Unless `--no-wrap` is specified, relative moves wrap around from the left-most to right-most and vice versa.", "除非指定 `--no-wrap`，相对移动会在最左与最右之间循环。"),
    ("When used with tab-relative, prevents wrapping around and will instead clamp to the left-most when moving left or right-most when moving right", "与 tab-relative 同用时禁止循环，向左移动钳制到最左、向右移动钳制到最右"),
    ("Don't automatically start the server", "不自动启动服务端"),
    ("How to manage passing the escape through to tmux", "如何把转义序列透传给 tmux"),
    ("Which shell to generate for", "要为哪个 shell 生成"),
    # ---- CLI 帮助补遗 ----
    ("Override the position for the initial window launched by this process.", "覆盖本进程启动的首个窗口的位置。"),
    (
        "Note that Wayland does not allow applications to control window positioning.",
        "注意 Wayland 不允许应用程序控制窗口位置。",
    ),
    ("Specify the target tab by its id", "按 id 指定目标标签页"),
    ("Zooms the pane if it wasn't already zoomed", "若窗格未处于缩放状态则缩放之"),
    ("Resizing animated images will reduce the image to a single frame.", "调整动图尺寸会将其降为单帧。"),
    (
        "Specify the filtering technique used when resizing/resampling images.  The default is a reasonable middle ground of speed and quality.",
        "指定缩放/重采样图片时使用的过滤算法。默认在速度与质量之间取折中。",
    ),
    (
        "The `--resample-filter` and `--resample-format` options give some control over the quality of the resizing operation and the image format used.",
        "`--resample-filter` 与 `--resample-format` 选项可对缩放质量与输出图片格式做一定控制。",
    ),
    ("Output a PEM file encoded copy of the credentials.", "输出 PEM 编码的凭据副本。"),
    (
        "They will be valid for the lifetime of the mux server process.",
        "凭据在 mux 服务端进程生命周期内有效。",
    ),
    (
        "Take care with them, as anyone with them will be able to connect directly to your mux server via the network and start a shell with no additional authentication.",
        "请妥善保管：持有凭据者可经网络直连你的 mux 服务端并启动 shell，无需其它认证。",
    ),
    (
        "Instead of executing your shell, run PROG. For example: `wezterm cli split-pane -- bash -l` will spawn bash as if it were a login shell",
        "不执行你的 shell，而是运行 PROG。例如：`wezterm cli split-pane -- bash -l` 会以登录 shell 的方式启动 bash",
    ),
    (
        "Instead of executing your shell, run PROG. For example: `wezterm cli spawn -- bash -l` will spawn bash as if it were a login shell",
        "不执行你的 shell，而是运行 PROG。例如：`wezterm cli spawn -- bash -l` 会以登录 shell 的方式启动 bash",
    ),
    (
        "split the current pane.\nOutputs the pane-id for the newly created pane on success",
        "拆分当前窗格。\n成功时输出新建窗格的 pane-id",
    ),
    (
        "Pre-process the image to resize it to the specified dimensions, expressed as eg: 800x600 (width x height). The resize is independent of other parameters that control the image placement and dimensions in the terminal; this is provided as a convenience preprocessing step.",
        "预处理图片，缩放到指定尺寸，例如 800x600（宽x高）。该缩放与控制图片在终端中位置和尺寸的其它参数相互独立，仅作为便捷的预处理步骤提供。",
    ),
    (
        "Specify the image format to use to encode resampled/resized images.  The default is to match the input format, but you can choose an alternative format",
        "指定重采样/缩放后图片的编码格式。默认与输入格式一致，也可选择其它格式",
    ),
    (
        "When resampling or resizing, display some diagnostics around the timing/performance of that operation",
        "重采样或缩放时显示该操作耗时/性能的诊断信息",
    ),
    (
        "See <https://docs.rs/image/latest/image/imageops/enum.FilterType.html#examples> for examples of the different techniques and their tradeoffs.",
        "各算法的效果与取舍示例见 <https://docs.rs/image/latest/image/imageops/enum.FilterType.html#examples>。",
    ),
    (
        "Instead of executing your shell, run PROG. For example: `wezterm start -- bash -l` will spawn bash as if it were a login shell. [aliases: -e]",
        "不执行你的 shell，而是运行 PROG。例如：`wezterm start -- bash -l` 会以登录 shell 的方式启动 bash。[别名: -e]",
    ),
    (
        "Override specific SSH configuration options. `wezterm ssh` is able to parse some (but not all!) options from your `~/.ssh/config` and `/etc/ssh/ssh_config` files. This command line switch allows you to override or otherwise specify ssh_config style options.\n\nFor example:\n\n`wezterm ssh -oIdentityFile=/secret/id_ed25519 some-host`",
        "覆盖指定的 SSH 配置项。`wezterm ssh` 能解析 `~/.ssh/config` 与 `/etc/ssh/ssh_config` 中的部分（不是全部！）选项，此开关允许你覆盖或补充 ssh_config 风格的选项。\n\n例如：\n\n`wezterm ssh -oIdentityFile=/secret/id_ed25519 some-host`",
    ),
    (
        "Override the position for the initial window launched by this process.\n\n--position 10,20          to set x=10, y=20 in screen coordinates\n--position screen:10,20   to set x=10, y=20 in screen coordinates\n--position main:10,20     to set x=10, y=20 relative to the main monitor\n--position active:10,20   to set x=10, y=20 relative to the active monitor\n--position HDMI-1:10,20   to set x=10, y=20 relative to the monitor named HDMI-1\n\nNote that Wayland does not allow applications to control window positioning.",
        "覆盖本进程启动的首个窗口的位置。\n\n--position 10,20          屏幕坐标 x=10, y=20\n--position screen:10,20   屏幕坐标 x=10, y=20\n--position main:10,20     相对主显示器的 x=10, y=20\n--position active:10,20   相对当前活动显示器的 x=10, y=20\n--position HDMI-1:10,20   相对名为 HDMI-1 的显示器的 x=10, y=20\n\n注意 Wayland 不允许应用程序控制窗口位置。",
    ),
    # ---- settings overlay (fork) ----
    ("Settings", "设置"),
    ("Language", "语言"),
    ("Appearance", "外观"),
    ("Interaction", "交互"),
    ("Font", "字体"),
    ("Font size", "字号"),
    ("Right-click menu", "右键菜单"),
    ("Scroll bar", "滚动条"),
    ("Audible bell", "响铃"),
    ("Close confirmation", "关闭确认"),
    ("On", "开"),
    ("Off", "关"),
    ("System beep", "系统提示音"),
    ("Disabled", "已禁用"),
    ("Always prompt", "总是询问"),
    ("Never prompt", "从不询问"),
    ("(no matches)", "（无匹配项）"),
    ("↑↓ select  Tab section  Enter apply  Esc cancel", "↑↓ 选择  Tab 切换分区  Enter 应用  Esc 取消"),
    ("Zooms the current Pane", "缩放当前窗格"),
    ("Un-Zooms the current Pane", "取消当前窗格缩放"),
    # ---- command palette: static docs ----
    ("Pastes text from the primary selection", "粘贴主选区中的文本"),
    ("Copies text to the primary selection", "将文本复制到主选区"),
    ("Copies text to the clipboard", "将文本复制到剪贴板"),
    ("Copies text to the clipboard and the primary selection", "将文本复制到剪贴板和主选区"),
    ("Pastes text from the clipboard", "粘贴剪贴板中的文本"),
    ("Switch between normal and full screen mode", "在普通与全屏模式间切换"),
    (
        "Toggles the window between floating and non-floating states to stay on top of other windows.",
        "切换窗口是否悬浮于其它窗口之上。",
    ),
    ("Toggles the window to remain behind all other windows.", "切换窗口是否保持在所有窗口之下。"),
    ("Set the window level to be on top of other windows.", "将窗口层级设为置于其它窗口之上。"),
    ("Set window level to normal", "将窗口层级设为普通"),
    ("Set window to remain behind all other windows.", "将窗口设为保持在所有窗口之下。"),
    ("Hides/Mimimizes the current window", "隐藏/最小化当前窗口"),
    ("Show/Restore the current window", "显示/恢复当前窗口"),
    ("Hides all of the windows of the application. This is macOS specific.", "隐藏应用的所有窗口（仅 macOS）。"),
    ("Launches the default program into a new window", "在新窗口中启动默认程序"),
    (
        "Clears any text that has scrolled out of the viewport of the current pane",
        "清除当前窗格中已滚出可视区的文本",
    ),
    ("Removes all content from the screen and scrollback", "清除屏幕与回滚缓冲中的所有内容"),
    ("Enters the search mode UI for the current pane", "进入当前窗格的搜索界面"),
    ("Activates the debug overlay and Lua REPL", "打开调试浮层与 Lua REPL"),
    ("Activates the selector overlay and wait for input", "打开选择器浮层并等待输入"),
    ("Activates the confirmation overlay and wait for input", "打开确认浮层并等待输入"),
    ("Activates the prompt overlay and wait for input", "打开输入浮层并等待输入"),
    ("Activates the quick selection UI for the current pane", "打开当前窗格的快速选择界面"),
    ("Activates the character selection UI for the current pane", "打开当前窗格的字符选择界面"),
    ("Activates the pane selection UI", "打开窗格选择界面"),
    ("Scales the font size smaller by 10%", "字号缩小 10%"),
    ("Scales the font size larger by 10%", "字号放大 10%"),
    ("Restores the font size to match your configuration file", "恢复为配置文件中的字号"),
    ("Restores the original window and font size", "恢复初始窗口与字号"),
    ("Create a new tab in the same domain as the current pane", "在当前窗格所在的域中新建标签页"),
    ("Create a new tab in the default domain", "在默认域中新建标签页"),
    ("Activates the tab on the far right", "激活最右侧的标签页"),
    (
        "Closes the current tab, terminating all the processes that are running in its panes.",
        "关闭当前标签页，并终止其所有窗格中运行的进程。",
    ),
    (
        "Closes the current pane, terminating the processes that are running inside it.",
        "关闭当前窗格，并终止其中运行的进程。",
    ),
    (
        "Activates the preceeding window. If this is the first window then cycles around and activates last window",
        "激活上一个窗口；若已是第一个窗口则循环激活最后一个窗口",
    ),
    (
        "Activates the next window. If this is the last window then cycles around and activates first window",
        "激活下一个窗口；若已是最后一个窗口则循环激活第一个窗口",
    ),
    ("Activates the preceeding window, stopping at the first window", "激活上一个窗口，到第一个窗口为止"),
    ("Activates the next window, stopping at the last window", "激活下一个窗口，到最后一个窗口为止"),
    (
        "Activates the tab to the left. If this is the left-most tab then cycles around and activates the right-most tab",
        "激活左侧标签页；若已是最左侧则循环激活最右侧标签页",
    ),
    (
        "Activates the tab to the right. If this is the right-most tab then cycles around and activates the left-most tab",
        "激活右侧标签页；若已是最右侧则循环激活最左侧标签页",
    ),
    ("Activates the tab to the left. Stopping at the left-most tab", "激活左侧标签页，到最左侧为止"),
    ("Activates the tab to the right. Stopping at the right-most tab", "激活右侧标签页，到最右侧为止"),
    ("Reloads the configuration file", "重新加载配置文件"),
    ("Quits WezTerm", "退出 WezTerm"),
    ("Rearranges the tabs so that the current tab moves one place to the left", "重排标签页，将当前标签页左移一位"),
    ("Rearranges the tabs so that the current tab moves one place to the right", "重排标签页，将当前标签页右移一位"),
    ("Scrolls the viewport up by 1 page", "可视区向上滚动一页"),
    ("Scrolls the viewport down by 1 page", "可视区向下滚动一页"),
    ("Scrolls to the bottom of the viewport", "滚动到可视区底部"),
    ("Scrolls to the top of the viewport", "滚动到可视区顶部"),
    ("Enter mouse-less copy mode to select text using only the keyboard", "进入无鼠标复制模式，仅用键盘选择文本"),
    (
        "Split the current pane vertically into two panes, by spawning the default program into the bottom half",
        "将当前窗格垂直拆分为两个窗格，默认程序启动在下半部分",
    ),
    (
        "Split the current pane horizontally into two panes, by spawning the default program into the right hand side",
        "将当前窗格水平拆分为两个窗格，默认程序启动在右半部分",
    ),
    (
        "Split the current pane veritically into two panes, by spawning the default program into the bottom",
        "将当前窗格垂直拆分为两个窗格，默认程序启动在下半部分",
    ),
    ("Adjusts the closest split divider to the left", "将最近的分隔条向左调整"),
    ("Adjusts the closest split divider to the right", "将最近的分隔条向右调整"),
    ("Adjusts the closest split divider towards the top", "将最近的分隔条向上调整"),
    ("Adjusts the closest split divider towards the bottom", "将最近的分隔条向下调整"),
    ("Activates the pane to the left of the current pane", "激活当前窗格左侧的窗格"),
    ("Activates the pane to the right of the current pane", "激活当前窗格右侧的窗格"),
    ("Activates the pane to the top of the current pane", "激活当前窗格上方的窗格"),
    ("Activates the pane to the bottom of the current pane", "激活当前窗格下方的窗格"),
    ("Toggles the zoom state for the current pane", "切换当前窗格的缩放状态"),
    ("If there was no prior active tab, has no effect.", "若之前没有活动过的标签页，则无效果。"),
    ("Removes all entries from the stack", "移除栈中的所有条目"),
    ("If there is no link under the mouse cursor, has no effect.", "若鼠标处没有链接，则无效果。"),
    ("Shows the launcher menu", "显示启动器菜单"),
    ("Shows the tab navigator", "显示标签页导航器"),
    ("Detaches (disconnects from) the domain of the active pane", "脱离（断开）活动窗格所在的域"),
    ("Detaches (disconnects from) the default domain", "脱离（断开）默认域"),
    ("Visit the wezterm documentation website", "访问 wezterm 文档网站"),
    ("Visit wezterm's GitHub discussion", "访问 wezterm 的 GitHub 讨论"),
    ("Visit wezterm's GitHub issues", "访问 wezterm 的 GitHub 问题页"),
    ("Has no effect", "无任何效果"),
    ("Requests a window drag operation from the window environment", "请求窗口环境发起窗口拖拽"),
    ("Performs multiple nested actions", "依次执行多个嵌套动作"),
    (
        "Places the current pane into the zoomed state, filling all of the space in the tab",
        "将当前窗格置为缩放状态，占满标签页的全部空间",
    ),
    ("Takes the current pane out of the zoomed state", "将当前窗格退出缩放状态"),
    ("Emits the named event, causing any associated event handler(s) to trigger", "发出命名事件，触发关联的事件处理器"),
    # ---- dynamic templates ----
    ("{label} (New Tab)", "{label}（新建标签页）"),
    ("New Tab (Domain {label})", "新建标签页（域 {label}）"),
    ("Attach Domain {label}", "附加域 {label}"),
    ("Detach Domain {label}", "脱离域 {label}"),
    ("Switch to workspace {workspace}", "切换到工作区 {workspace}"),
    ("Pipe selection to {cmd}", "将选区管道传给 {cmd}"),
    ("Pipe the selection to the standard input of {cmd}", "将选区通过管道传给 {cmd} 的标准输入"),
    ("New Tab (`{name}` Domain)", "新建标签页（域 `{name}`）"),
    ("Create a new tab in the domain named {name}", "在名为 {name} 的域中新建标签页"),
    ("New Tab (Domain with id {id})", "新建标签页（域 id {id}）"),
    ("Create a new tab in the domain with id {id}", "在 id 为 {id} 的域中新建标签页"),
    ("Spawn a new Tab with {cmd}", "用 {cmd} 新建标签页"),
    ("Spawn a new Window with {cmd}", "用 {cmd} 新建窗口"),
    ("Activate {ordinal} Tab", "激活{ordinal}标签页"),
    ("Activates the {ordinal} tab", "激活{ordinal}标签页"),
    ("Activate {ordinal} Pane", "激活{ordinal}窗格"),
    ("Activates the {ordinal} Pane", "激活{ordinal}窗格"),
    ("Activate {ordinal} Window", "激活{ordinal}窗口"),
    ("Activates the {ordinal} window", "激活{ordinal}窗口"),
    ("Activate the {ordinal} window {direction}", "{direction}激活{ordinal}窗口"),
    (
        "Activates the {ordinal} window, moving {direction}. Wraps around to the other end",
        "{direction}激活{ordinal}窗口，到端点后循环",
    ),
    ("Activates the {ordinal} window, moving {direction}.", "{direction}激活{ordinal}窗口。"),
    ("Activate the {ordinal} tab to the {direction}", "激活{direction}的{ordinal}标签页"),
    (
        "Activates the {ordinal} tab to the {direction}. Wraps around to the other end",
        "激活{direction}的{ordinal}标签页，到端点后循环",
    ),
    ("Activates the {ordinal} tab to the {direction}", "激活{direction}的{ordinal}标签页"),
    ("Move tab {amount} place(s) to the {direction}", "标签页向{direction}移动 {amount} 位"),
    (
        "Rearranges the tabs so that the current tab moves {amount} place(s) to the {direction}",
        "重排标签页，将当前标签页向{direction}移动 {amount} 位",
    ),
    ("Move tab to index {n}", "移动标签页到第 {n} 位"),
    ("Rearranges the tabs so that the current tab moves to position {n}", "重排标签页，将当前标签页移到第 {n} 位"),
    ("Scroll Up {amount} Page(s)", "向上滚动 {amount} 页"),
    ("Scrolls the viewport up by {amount} pages", "可视区向上滚动 {amount} 页"),
    ("Scroll Down {amount} Page(s)", "向下滚动 {amount} 页"),
    ("Scrolls the viewport down by {amount} pages", "可视区向下滚动 {amount} 页"),
    ("Scroll {direction} {amount} line(s)", "向{direction}滚动 {amount} 行"),
    ("Scrolls the viewport {direction} by {amount} line(s)", "可视区向{direction}滚动 {amount} 行"),
    ("Scroll {direction} {amount} prompt(s)", "向{direction}滚动 {amount} 个提示符"),
    (
        "Scrolls the viewport {direction} to the {ordinal} semantic prompt zone in that direction",
        "可视区向{direction}滚动到该方向{ordinal}语义提示区",
    ),
    ("Resize Pane {amount} cell(s) to the Left", "向左调整窗格大小 {amount} 格"),
    ("Resize Pane {amount} cell(s) to the Right", "向右调整窗格大小 {amount} 格"),
    ("Resize Pane {amount} cell(s) Upwards", "向上调整窗格大小 {amount} 格"),
    ("Resize Pane {amount} cell(s) Downwards", "向下调整窗格大小 {amount} 格"),
    ("Detach the `{name}` domain", "脱离 `{name}` 域"),
    ("Detaches (disconnects from) the domain named `{name}`", "脱离（断开）名为 `{name}` 的域"),
    ("Detach the domain with id {id}", "脱离 id 为 {id} 的域"),
    ("Detaches (disconnects from) the domain with id {id}", "脱离（断开）id 为 {id} 的域"),
    ("Open {uri} in your browser", "在浏览器中打开 {uri}"),
    ("Sends `{text}` to the active pane, as though you typed it", "向活动窗格发送 `{text}`，如同手动输入"),
    ("Sends {key} to the active pane, as though you typed it", "向活动窗格发送按键 {key}，如同手动输入"),
    ("Selects text at the mouse cursor location using {mode}", "以 {mode} 方式选择鼠标位置处的文本"),
    ("Extends the selection text to the mouse cursor location using {mode}", "以 {mode} 方式将选区扩展到鼠标位置"),
    ("Completes selection, and copy {destination}", "完成选择并复制到 {destination}"),
    ("Completes text selection using the mouse, and copies to {destination}", "完成鼠标文本选择，并复制到 {destination}"),
    ("Open a URL or Completes selection by copying to {destination}", "打开链接，或完成选择并复制到 {destination}"),
    (
        "If the mouse is over a link, open it, otherwise, completes text selection using the mouse, and copies to {destination}",
        "若鼠标在链接上则打开链接，否则完成鼠标文本选择并复制到 {destination}",
    ),
    ("Spawn the default program into a new workspace and switch to it", "在新工作区启动默认程序并切换过去"),
    (
        "Switch to workspace `{name}`, spawn the default program if that workspace doesn't already exist",
        "切换到工作区 `{name}`，若不存在则启动默认程序",
    ),
    (
        "Switch to workspace `{name}`, spawn {prog} if that workspace doesn't already exist",
        "切换到工作区 `{name}`，若不存在则启动 {prog}",
    ),
    ("Spawn the {prog} into a new workspace and switch to it", "在新工作区启动 {prog} 并切换过去"),
    ("Switch to {ordinal} {direction} workspace", "切换到{direction}{ordinal}工作区"),
    (
        "Switch to the {ordinal} {direction} workspace, ordered lexicographically by workspace name",
        "切换到{direction}{ordinal}工作区（按名称字典序排列）",
    ),
    ("Activate key table `{name}`", "激活键表 `{name}`"),
    ("Attach domain `{name}`", "附加域 `{name}`"),
    ("Emit event `{name}`", "触发事件 `{name}`"),
    ("Rotate panes {direction}", "旋转窗格（{direction}）"),
    ("Split the current pane {direction}", "向{direction}拆分当前窗格"),
    # ---- direction / ordinal words ----
    ("left", "左"),
    ("right", "右"),
    ("up", "上"),
    ("down", "下"),
    ("backwards", "向后"),
    ("forwards", "向前"),
    ("previous", "上一个"),
    ("next", "下一个"),
    # ---- menubar group names ----
    ("WezTerm", "WezTerm"),
    ("Shell", "Shell"),
    ("Edit", "编辑"),
    ("View", "视图"),
    ("Window", "窗口"),
    ("Help", "帮助"),
    ("Workspace", "工作区"),
    ("Select Tab", "选择标签页"),
    ("Select Window", "选择窗口"),
    ("Select Pane", "选择窗格"),
    ("Move Tab", "移动标签页"),
    ("Resize Pane", "调整窗格"),
    ("Rotate Pane", "旋转窗格"),
    ("Copy Mode", "复制模式"),
    ("Attach", "附加"),
    ("Detach", "脱离"),
    ("Font Size", "字号"),
    ("Level", "层级"),
    # ---- context menu (fork) ----
    ("Split Pane Right", "向右分屏"),
    ("Split Pane Down", "向下分屏"),
    ("Copy", "复制"),
    ("Paste", "粘贴"),
    ("Scroll to Top", "滚动到顶部"),
    ("Scroll to Bottom", "滚动到底部"),
    ("Close Pane", "关闭窗格"),
    ("Show Tab Navigator", "显示标签页导航器"),
    ("Move Tab Left", "标签页左移"),
    ("Move Tab Right", "标签页右移"),
    ("Close Tab {n}", "关闭标签页 {n}"),
    ("Show Launcher", "显示启动器"),
    # ---- confirmations ----
    ("🛑 Really kill this pane?", "🛑 确实要关闭此窗格？"),
    ("🛑 Really kill this tab and all contained panes?", "🛑 确实要关闭此标签页及其所有窗格？"),
    ("🛑 Really kill this window and all contained tabs and panes?", "🛑 确实要关闭此窗口及其所有标签页和窗格？"),
    ("🛑 Really Quit WezTerm?", "🛑 确实要退出 WezTerm？"),
    (" [Y]es ", " [Y]是 "),
    (" [N]o ", " [N]否 "),
    # ---- copy mode / search ----
    ("Copy mode: {title}", "复制模式：{title}"),
    ("Search: {pattern} ({cur}/{total} matches. {mode}{remain})", "搜索：{pattern}（第 {cur}/{total} 个匹配。{mode}{remain}）"),
    ("Search: {pattern} ({cur}/{total} matches. {mode})", "搜索：{pattern}（第 {cur}/{total} 个匹配。{mode}）"),
    (" searching {remain} lines", " 正在搜索剩余 {remain} 行"),
    ("case-sensitive", "区分大小写"),
    ("ignore-case", "忽略大小写"),
    ("smart-case", "智能大小写"),
    ("regex", "正则"),
    # ---- quick select ----
    (
        "Select: {input}  (type highlighted prefix to {action}, uppercase pastes, ESC to cancel)",
        "选择：{input}（输入高亮前缀即可{action}，大写前缀直接粘贴，ESC 取消）",
    ),
    ("copy", "复制"),
    # ---- launcher ----
    ("Launcher", "启动器"),
    ("Tab Navigator", "标签页导航器"),
    ("Select an item and press Enter=launch  Esc=cancel  /=filter", "选择条目后 Enter=启动  Esc=取消  /=过滤"),
    ("Fuzzy matching: ", "模糊匹配："),
    ("(default shell)", "（默认 shell）"),
    ("domain `{name}`", "域 `{name}`"),
    ("domain `{name}` - {label}", "域 `{name}` - {label}"),
    ("New Tab ({label})", "新建标签页（{label}）"),
    ("Attach {label}", "附加 {label}"),
    ("Switch to workspace: `{ws}`", "切换到工作区：`{ws}`"),
    ("Create new Workspace (current is `{ws}`)", "新建工作区（当前为 `{ws}`）"),
    ("Create new Workspace", "新建工作区"),
    ("{title}. {n} panes", "{title}。{n} 个窗格"),
    # ---- debug overlay ----
    ("Debug", "调试"),
    ("Debug Overlay", "调试浮层"),
    ("Enter lua statements or expressions and hit Enter.", "输入 Lua 语句或表达式后按回车。"),
    ("Press ESC or CTRL-D to exit", "按 ESC 或 CTRL-D 退出"),
    # ---- char select groups ----
    ("Recent", "最近使用"),
    ("Emotion", "表情"),
    ("People", "人物"),
    ("Animals", "动物"),
    ("Food", "食物"),
    ("Travel", "旅行"),
    ("Activities", "活动"),
    ("Objects", "物品"),
    ("Symbols", "符号"),
    ("Flags", "旗帜"),
    ("NerdFonts", "Nerd 字体"),
    ("Unicode", "Unicode"),
    ("Short Codes", "短代码"),
    # ---- config error / fatal toasts ----
    ("(this window will close automatically)", "（此窗口将自动关闭）"),
    ("Failed: {err}", "失败：{err}"),
    ("wezterm Configuration Error", "wezterm 配置错误"),
    ("Wezterm panic", "Wezterm 崩溃"),
    ("Wezterm Error", "Wezterm 错误"),
]


def esc(s: str) -> str:
    return (s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n"))


def main() -> None:
    pairs = sorted(PAIRS, key=lambda p: p[0].encode("utf-8"))
    keys = [k for k, _ in pairs]
    assert len(keys) == len(set(keys)), "duplicate keys!"
    print("//! zh-CN 译表：按 key（英文原文）字典序排序，binary_search 查找。")
    print("//! 新增条目必须保持有序（`i18n::tests::zh_table_sorted_unique` 守门）；")
    print("//! 重建用 `python3 scripts/gen_zh_table.py`（见脚本内说明）。")
    print("//! 带参数的文案存 `{name}` 模板，取词后经 `i18n::fill` 填参。")
    print()
    print("use std::borrow::Cow;")
    print()
    print("pub(crate) static ZH_CN: &[(&str, &str)] = &[")
    for key, value in pairs:
        print(f'    ("{esc(key)}", "{esc(value)}"),')
    print("];")
    print()
    print("/// Look up `key` in the zh-CN table, falling back to the key itself")
    print("pub fn translate(key: &'static str) -> Cow<'static, str> {")
    print("    ZH_CN")
    print("        .binary_search_by(|(k, _)| (*k).cmp(key))")
    print("        .ok()")
    print("        .map(|idx| Cow::Borrowed(ZH_CN[idx].1))")
    print("        .unwrap_or(Cow::Borrowed(key))")
    print("}")


if __name__ == "__main__":
    main()
