#!/usr/bin/env python3
"""One-shot generator for config/src/i18n/zh_cn.rs (fork).

Takes the (english_key, zh_cn) pairs below, byte-sorts by key and emits
the ZH_CN static slice so the `zh_table_sorted_unique` test can never
drift.  Run manually when adding entries; the output is committed.

    python3 scripts/gen_zh_table.py > config/src/i18n/zh_cn.rs
"""

PAIRS = [
    # ---- command palette: static briefs ----
    ("Paste primary selection", "粘贴主选区"),
    ("Copy to primary selection", "复制到主选区"),
    ("Copy to clipboard", "复制到剪贴板"),
    ("Copy to clipboard and primary selection", "复制到剪贴板和主选区"),
    ("Paste from clipboard", "从剪贴板粘贴"),
    ("Toggle full screen mode", "切换全屏模式"),
    ("Toggle always on Top", "切换窗口置顶"),
    ("Toggle always on Bottom", "切换窗口置底"),
    ("Always on Top", "窗口置顶"),
    ("Normal", "普通层级"),
    ("Always on Bottom", "窗口置底"),
    ("Hide/Minimize Window", "隐藏/最小化窗口"),
    ("Show/Restore Window", "显示/恢复窗口"),
    ("Hide Application", "隐藏应用"),
    ("New Window", "新建窗口"),
    ("Clear scrollback", "清除回滚缓冲"),
    ("Clear the scrollback and viewport", "清除回滚缓冲与可视区"),
    ("Search pane output", "搜索窗格输出"),
    ("Show debug overlay", "显示调试浮层"),
    ("Prompt the user to choose from a list", "弹出列表让用户选择"),
    ("Prompt the user for confirmation", "弹出确认对话框"),
    ("Prompt the user for a line of text", "弹出单行文本输入"),
    ("Enter QuickSelect mode", "进入快速选择模式"),
    ("Enter Emoji / Character selection mode", "进入 Emoji / 字符选择模式"),
    ("Enter Pane selection mode", "进入窗格选择模式"),
    ("Swap a pane with the active pane", "交换窗格与活动窗格"),
    ("Swap a pane with the active pane, keeping focus", "交换窗格与活动窗格（保持焦点）"),
    ("Move a pane into its own tab", "将窗格移到独立标签页"),
    ("Move a pane into its own window", "将窗格移到独立窗口"),
    ("Decrease font size", "减小字号"),
    ("Increase font size", "增大字号"),
    ("Reset font size", "重置字号"),
    ("Reset the window and font size", "重置窗口与字号"),
    ("New Tab", "新建标签页"),
    ("New Tab (Default Domain)", "新建标签页（默认域）"),
    ("Activate right-most tab", "激活最右侧标签页"),
    ("Close current Tab", "关闭当前标签页"),
    ("Close current Pane", "关闭当前窗格"),
    ("Activate the preceeding window", "激活上一个窗口"),
    ("Activate the next window", "激活下一个窗口"),
    ("Activate the tab to the left", "激活左侧标签页"),
    ("Activate the tab to the right", "激活右侧标签页"),
    ("Activate the tab to the left (no wrapping)", "激活左侧标签页（不循环）"),
    ("Activate the tab to the right (no wrapping)", "激活右侧标签页（不循环）"),
    ("Reload configuration", "重载配置"),
    ("Quit WezTerm", "退出 WezTerm"),
    ("Move tab one place to the left", "标签页左移一位"),
    ("Move tab one place to the right", "标签页右移一位"),
    ("Scroll Up One Page", "向上滚动一页"),
    ("Scroll Down One Page", "向下滚动一页"),
    (
        "Scrolls based on the mouse wheel position in the current mouse event",
        "按当前鼠标事件中的滚轮增量滚动",
    ),
    ("Scroll to the bottom", "滚动到底部"),
    ("Scroll to the top", "滚动到顶部"),
    ("Activate Copy Mode", "进入复制模式"),
    ("Split Vertically (Top/Bottom)", "垂直分屏（上/下）"),
    ("Split Horizontally (Left/Right)", "水平分屏（左/右）"),
    ("Activate Pane Left", "激活左侧窗格"),
    ("Activate Pane Right", "激活右侧窗格"),
    ("Activate Pane Up", "激活上方窗格"),
    ("Activate Pane Down", "激活下方窗格"),
    ("Toggle Pane Zoom", "切换窗格缩放"),
    ("Activate the last active tab", "激活最近活动的标签页"),
    ("Clear the key table stack", "清空键表栈"),
    ("Open link at mouse cursor", "打开鼠标处的链接"),
    ("Show the launcher", "显示启动器"),
    ("Navigate tabs", "浏览标签页"),
    ("Detach the domain of the active pane", "脱离活动窗格所在的域"),
    ("Detach the default domain", "脱离默认域"),
    ("Documentation", "文档"),
    ("Discuss on GitHub", "到 GitHub 讨论"),
    ("Search or report issue on GitHub", "在 GitHub 搜索或报告问题"),
    ("Does nothing", "无操作"),
    ("Clears the selection in the current pane", "清除当前窗格的选区"),
    ("Pop the current key table", "弹出当前键表"),
    ("Reset the terminal emulation state in the current pane", "重置当前窗格的终端仿真状态"),
    ("Activate Command Palette", "打开命令面板"),
    ("Shows the command palette modal", "显示命令面板浮层"),
    ("Open Settings", "打开设置"),
    ("Shows the settings overlay", "显示设置浮层"),
    ("Show Main Menu", "打开主菜单"),
    ("Shows the main menu overlay", "显示主菜单浮层"),
    ("Show Keybindings", "查看快捷键"),
    ("Shows the keybinding cheat sheet overlay", "显示快捷键速查浮层"),
    ("Keybindings", "快捷键"),
    ("↑↓ scroll  Esc close", "↑↓ 滚动  Esc 关闭"),
    # ---- settings overlay (fork) ----
    ("Settings", "设置"),
    ("Language", "语言"),
    ("Appearance", "外观"),
    ("Interaction", "交互"),
    ("Font", "字体"),
    ("Font size", "字号"),
    ("Right-click menu", "右键菜单"),
    ("Scroll bar", "滚动条"),
    ("Audible bell", "响铃"),
    ("Close confirmation", "关闭确认"),
    ("On", "开"),
    ("Off", "关"),
    ("System beep", "系统提示音"),
    ("Disabled", "已禁用"),
    ("Always prompt", "总是询问"),
    ("Never prompt", "从不询问"),
    ("(no matches)", "（无匹配项）"),
    ("↑↓ select  Tab section  Enter apply  Esc cancel", "↑↓ 选择  Tab 切换分区  Enter 应用  Esc 取消"),
    ("Zooms the current Pane", "缩放当前窗格"),
    ("Un-Zooms the current Pane", "取消当前窗格缩放"),
    # ---- command palette: static docs ----
    ("Pastes text from the primary selection", "粘贴主选区中的文本"),
    ("Copies text to the primary selection", "将文本复制到主选区"),
    ("Copies text to the clipboard", "将文本复制到剪贴板"),
    ("Copies text to the clipboard and the primary selection", "将文本复制到剪贴板和主选区"),
    ("Pastes text from the clipboard", "粘贴剪贴板中的文本"),
    ("Switch between normal and full screen mode", "在普通与全屏模式间切换"),
    (
        "Toggles the window between floating and non-floating states to stay on top of other windows.",
        "切换窗口是否悬浮于其它窗口之上。",
    ),
    ("Toggles the window to remain behind all other windows.", "切换窗口是否保持在所有窗口之下。"),
    ("Set the window level to be on top of other windows.", "将窗口层级设为置于其它窗口之上。"),
    ("Set window level to normal", "将窗口层级设为普通"),
    ("Set window to remain behind all other windows.", "将窗口设为保持在所有窗口之下。"),
    ("Hides/Mimimizes the current window", "隐藏/最小化当前窗口"),
    ("Show/Restore the current window", "显示/恢复当前窗口"),
    ("Hides all of the windows of the application. This is macOS specific.", "隐藏应用的所有窗口（仅 macOS）。"),
    ("Launches the default program into a new window", "在新窗口中启动默认程序"),
    (
        "Clears any text that has scrolled out of the viewport of the current pane",
        "清除当前窗格中已滚出可视区的文本",
    ),
    ("Removes all content from the screen and scrollback", "清除屏幕与回滚缓冲中的所有内容"),
    ("Enters the search mode UI for the current pane", "进入当前窗格的搜索界面"),
    ("Activates the debug overlay and Lua REPL", "打开调试浮层与 Lua REPL"),
    ("Activates the selector overlay and wait for input", "打开选择器浮层并等待输入"),
    ("Activates the confirmation overlay and wait for input", "打开确认浮层并等待输入"),
    ("Activates the prompt overlay and wait for input", "打开输入浮层并等待输入"),
    ("Activates the quick selection UI for the current pane", "打开当前窗格的快速选择界面"),
    ("Activates the character selection UI for the current pane", "打开当前窗格的字符选择界面"),
    ("Activates the pane selection UI", "打开窗格选择界面"),
    ("Scales the font size smaller by 10%", "字号缩小 10%"),
    ("Scales the font size larger by 10%", "字号放大 10%"),
    ("Restores the font size to match your configuration file", "恢复为配置文件中的字号"),
    ("Restores the original window and font size", "恢复初始窗口与字号"),
    ("Create a new tab in the same domain as the current pane", "在当前窗格所在的域中新建标签页"),
    ("Create a new tab in the default domain", "在默认域中新建标签页"),
    ("Activates the tab on the far right", "激活最右侧的标签页"),
    (
        "Closes the current tab, terminating all the processes that are running in its panes.",
        "关闭当前标签页，并终止其所有窗格中运行的进程。",
    ),
    (
        "Closes the current pane, terminating the processes that are running inside it.",
        "关闭当前窗格，并终止其中运行的进程。",
    ),
    (
        "Activates the preceeding window. If this is the first window then cycles around and activates last window",
        "激活上一个窗口；若已是第一个窗口则循环激活最后一个窗口",
    ),
    (
        "Activates the next window. If this is the last window then cycles around and activates first window",
        "激活下一个窗口；若已是最后一个窗口则循环激活第一个窗口",
    ),
    ("Activates the preceeding window, stopping at the first window", "激活上一个窗口，到第一个窗口为止"),
    ("Activates the next window, stopping at the last window", "激活下一个窗口，到最后一个窗口为止"),
    (
        "Activates the tab to the left. If this is the left-most tab then cycles around and activates the right-most tab",
        "激活左侧标签页；若已是最左侧则循环激活最右侧标签页",
    ),
    (
        "Activates the tab to the right. If this is the right-most tab then cycles around and activates the left-most tab",
        "激活右侧标签页；若已是最右侧则循环激活最左侧标签页",
    ),
    ("Activates the tab to the left. Stopping at the left-most tab", "激活左侧标签页，到最左侧为止"),
    ("Activates the tab to the right. Stopping at the right-most tab", "激活右侧标签页，到最右侧为止"),
    ("Reloads the configuration file", "重新加载配置文件"),
    ("Quits WezTerm", "退出 WezTerm"),
    ("Rearranges the tabs so that the current tab moves one place to the left", "重排标签页，将当前标签页左移一位"),
    ("Rearranges the tabs so that the current tab moves one place to the right", "重排标签页，将当前标签页右移一位"),
    ("Scrolls the viewport up by 1 page", "可视区向上滚动一页"),
    ("Scrolls the viewport down by 1 page", "可视区向下滚动一页"),
    ("Scrolls to the bottom of the viewport", "滚动到可视区底部"),
    ("Scrolls to the top of the viewport", "滚动到可视区顶部"),
    ("Enter mouse-less copy mode to select text using only the keyboard", "进入无鼠标复制模式，仅用键盘选择文本"),
    (
        "Split the current pane vertically into two panes, by spawning the default program into the bottom half",
        "将当前窗格垂直拆分为两个窗格，默认程序启动在下半部分",
    ),
    (
        "Split the current pane horizontally into two panes, by spawning the default program into the right hand side",
        "将当前窗格水平拆分为两个窗格，默认程序启动在右半部分",
    ),
    (
        "Split the current pane veritically into two panes, by spawning the default program into the bottom",
        "将当前窗格垂直拆分为两个窗格，默认程序启动在下半部分",
    ),
    ("Adjusts the closest split divider to the left", "将最近的分隔条向左调整"),
    ("Adjusts the closest split divider to the right", "将最近的分隔条向右调整"),
    ("Adjusts the closest split divider towards the top", "将最近的分隔条向上调整"),
    ("Adjusts the closest split divider towards the bottom", "将最近的分隔条向下调整"),
    ("Activates the pane to the left of the current pane", "激活当前窗格左侧的窗格"),
    ("Activates the pane to the right of the current pane", "激活当前窗格右侧的窗格"),
    ("Activates the pane to the top of the current pane", "激活当前窗格上方的窗格"),
    ("Activates the pane to the bottom of the current pane", "激活当前窗格下方的窗格"),
    ("Toggles the zoom state for the current pane", "切换当前窗格的缩放状态"),
    ("If there was no prior active tab, has no effect.", "若之前没有活动过的标签页，则无效果。"),
    ("Removes all entries from the stack", "移除栈中的所有条目"),
    ("If there is no link under the mouse cursor, has no effect.", "若鼠标处没有链接，则无效果。"),
    ("Shows the launcher menu", "显示启动器菜单"),
    ("Shows the tab navigator", "显示标签页导航器"),
    ("Detaches (disconnects from) the domain of the active pane", "脱离（断开）活动窗格所在的域"),
    ("Detaches (disconnects from) the default domain", "脱离（断开）默认域"),
    ("Visit the wezterm documentation website", "访问 wezterm 文档网站"),
    ("Visit wezterm's GitHub discussion", "访问 wezterm 的 GitHub 讨论"),
    ("Visit wezterm's GitHub issues", "访问 wezterm 的 GitHub 问题页"),
    ("Has no effect", "无任何效果"),
    ("Requests a window drag operation from the window environment", "请求窗口环境发起窗口拖拽"),
    ("Performs multiple nested actions", "依次执行多个嵌套动作"),
    (
        "Places the current pane into the zoomed state, filling all of the space in the tab",
        "将当前窗格置为缩放状态，占满标签页的全部空间",
    ),
    ("Takes the current pane out of the zoomed state", "将当前窗格退出缩放状态"),
    ("Emits the named event, causing any associated event handler(s) to trigger", "发出命名事件，触发关联的事件处理器"),
    # ---- dynamic templates ----
    ("{label} (New Tab)", "{label}（新建标签页）"),
    ("New Tab (Domain {label})", "新建标签页（域 {label}）"),
    ("Attach Domain {label}", "附加域 {label}"),
    ("Detach Domain {label}", "脱离域 {label}"),
    ("Switch to workspace {workspace}", "切换到工作区 {workspace}"),
    ("Pipe selection to {cmd}", "将选区管道传给 {cmd}"),
    ("Pipe the selection to the standard input of {cmd}", "将选区通过管道传给 {cmd} 的标准输入"),
    ("New Tab (`{name}` Domain)", "新建标签页（域 `{name}`）"),
    ("Create a new tab in the domain named {name}", "在名为 {name} 的域中新建标签页"),
    ("New Tab (Domain with id {id})", "新建标签页（域 id {id}）"),
    ("Create a new tab in the domain with id {id}", "在 id 为 {id} 的域中新建标签页"),
    ("Spawn a new Tab with {cmd}", "用 {cmd} 新建标签页"),
    ("Spawn a new Window with {cmd}", "用 {cmd} 新建窗口"),
    ("Activate {ordinal} Tab", "激活{ordinal}标签页"),
    ("Activates the {ordinal} tab", "激活{ordinal}标签页"),
    ("Activate {ordinal} Pane", "激活{ordinal}窗格"),
    ("Activates the {ordinal} Pane", "激活{ordinal}窗格"),
    ("Activate {ordinal} Window", "激活{ordinal}窗口"),
    ("Activates the {ordinal} window", "激活{ordinal}窗口"),
    ("Activate the {ordinal} window {direction}", "{direction}激活{ordinal}窗口"),
    (
        "Activates the {ordinal} window, moving {direction}. Wraps around to the other end",
        "{direction}激活{ordinal}窗口，到端点后循环",
    ),
    ("Activates the {ordinal} window, moving {direction}.", "{direction}激活{ordinal}窗口。"),
    ("Activate the {ordinal} tab to the {direction}", "激活{direction}的{ordinal}标签页"),
    (
        "Activates the {ordinal} tab to the {direction}. Wraps around to the other end",
        "激活{direction}的{ordinal}标签页，到端点后循环",
    ),
    ("Activates the {ordinal} tab to the {direction}", "激活{direction}的{ordinal}标签页"),
    ("Move tab {amount} place(s) to the {direction}", "标签页向{direction}移动 {amount} 位"),
    (
        "Rearranges the tabs so that the current tab moves {amount} place(s) to the {direction}",
        "重排标签页，将当前标签页向{direction}移动 {amount} 位",
    ),
    ("Move tab to index {n}", "移动标签页到第 {n} 位"),
    ("Rearranges the tabs so that the current tab moves to position {n}", "重排标签页，将当前标签页移到第 {n} 位"),
    ("Scroll Up {amount} Page(s)", "向上滚动 {amount} 页"),
    ("Scrolls the viewport up by {amount} pages", "可视区向上滚动 {amount} 页"),
    ("Scroll Down {amount} Page(s)", "向下滚动 {amount} 页"),
    ("Scrolls the viewport down by {amount} pages", "可视区向下滚动 {amount} 页"),
    ("Scroll {direction} {amount} line(s)", "向{direction}滚动 {amount} 行"),
    ("Scrolls the viewport {direction} by {amount} line(s)", "可视区向{direction}滚动 {amount} 行"),
    ("Scroll {direction} {amount} prompt(s)", "向{direction}滚动 {amount} 个提示符"),
    (
        "Scrolls the viewport {direction} to the {ordinal} semantic prompt zone in that direction",
        "可视区向{direction}滚动到该方向{ordinal}语义提示区",
    ),
    ("Resize Pane {amount} cell(s) to the Left", "向左调整窗格大小 {amount} 格"),
    ("Resize Pane {amount} cell(s) to the Right", "向右调整窗格大小 {amount} 格"),
    ("Resize Pane {amount} cell(s) Upwards", "向上调整窗格大小 {amount} 格"),
    ("Resize Pane {amount} cell(s) Downwards", "向下调整窗格大小 {amount} 格"),
    ("Detach the `{name}` domain", "脱离 `{name}` 域"),
    ("Detaches (disconnects from) the domain named `{name}`", "脱离（断开）名为 `{name}` 的域"),
    ("Detach the domain with id {id}", "脱离 id 为 {id} 的域"),
    ("Detaches (disconnects from) the domain with id {id}", "脱离（断开）id 为 {id} 的域"),
    ("Open {uri} in your browser", "在浏览器中打开 {uri}"),
    ("Sends `{text}` to the active pane, as though you typed it", "向活动窗格发送 `{text}`，如同手动输入"),
    ("Sends {key} to the active pane, as though you typed it", "向活动窗格发送按键 {key}，如同手动输入"),
    ("Selects text at the mouse cursor location using {mode}", "以 {mode} 方式选择鼠标位置处的文本"),
    ("Extends the selection text to the mouse cursor location using {mode}", "以 {mode} 方式将选区扩展到鼠标位置"),
    ("Completes selection, and copy {destination}", "完成选择并复制到 {destination}"),
    ("Completes text selection using the mouse, and copies to {destination}", "完成鼠标文本选择，并复制到 {destination}"),
    ("Open a URL or Completes selection by copying to {destination}", "打开链接，或完成选择并复制到 {destination}"),
    (
        "If the mouse is over a link, open it, otherwise, completes text selection using the mouse, and copies to {destination}",
        "若鼠标在链接上则打开链接，否则完成鼠标文本选择并复制到 {destination}",
    ),
    ("Spawn the default program into a new workspace and switch to it", "在新工作区启动默认程序并切换过去"),
    (
        "Switch to workspace `{name}`, spawn the default program if that workspace doesn't already exist",
        "切换到工作区 `{name}`，若不存在则启动默认程序",
    ),
    (
        "Switch to workspace `{name}`, spawn {prog} if that workspace doesn't already exist",
        "切换到工作区 `{name}`，若不存在则启动 {prog}",
    ),
    ("Spawn the {prog} into a new workspace and switch to it", "在新工作区启动 {prog} 并切换过去"),
    ("Switch to {ordinal} {direction} workspace", "切换到{direction}{ordinal}工作区"),
    (
        "Switch to the {ordinal} {direction} workspace, ordered lexicographically by workspace name",
        "切换到{direction}{ordinal}工作区（按名称字典序排列）",
    ),
    ("Activate key table `{name}`", "激活键表 `{name}`"),
    ("Attach domain `{name}`", "附加域 `{name}`"),
    ("Emit event `{name}`", "触发事件 `{name}`"),
    ("Rotate panes {direction}", "旋转窗格（{direction}）"),
    ("Split the current pane {direction}", "向{direction}拆分当前窗格"),
    # ---- direction / ordinal words ----
    ("left", "左"),
    ("right", "右"),
    ("up", "上"),
    ("down", "下"),
    ("backwards", "向后"),
    ("forwards", "向前"),
    ("previous", "上一个"),
    ("next", "下一个"),
    # ---- menubar group names ----
    ("WezTerm", "WezTerm"),
    ("Shell", "Shell"),
    ("Edit", "编辑"),
    ("View", "视图"),
    ("Window", "窗口"),
    ("Help", "帮助"),
    ("Workspace", "工作区"),
    ("Select Tab", "选择标签页"),
    ("Select Window", "选择窗口"),
    ("Select Pane", "选择窗格"),
    ("Move Tab", "移动标签页"),
    ("Resize Pane", "调整窗格"),
    ("Rotate Pane", "旋转窗格"),
    ("Copy Mode", "复制模式"),
    ("Attach", "附加"),
    ("Detach", "脱离"),
    ("Font Size", "字号"),
    ("Level", "层级"),
    # ---- context menu (fork) ----
    ("Split Pane Right", "向右分屏"),
    ("Split Pane Down", "向下分屏"),
    ("Copy", "复制"),
    ("Paste", "粘贴"),
    ("Scroll to Top", "滚动到顶部"),
    ("Scroll to Bottom", "滚动到底部"),
    ("Close Pane", "关闭窗格"),
    ("Show Tab Navigator", "显示标签页导航器"),
    ("Move Tab Left", "标签页左移"),
    ("Move Tab Right", "标签页右移"),
    ("Close Tab {n}", "关闭标签页 {n}"),
    ("Show Launcher", "显示启动器"),
    # ---- confirmations ----
    ("🛑 Really kill this pane?", "🛑 确实要关闭此窗格？"),
    ("🛑 Really kill this tab and all contained panes?", "🛑 确实要关闭此标签页及其所有窗格？"),
    ("🛑 Really kill this window and all contained tabs and panes?", "🛑 确实要关闭此窗口及其所有标签页和窗格？"),
    ("🛑 Really Quit WezTerm?", "🛑 确实要退出 WezTerm？"),
    (" [Y]es ", " [Y]是 "),
    (" [N]o ", " [N]否 "),
    # ---- copy mode / search ----
    ("Copy mode: {title}", "复制模式：{title}"),
    ("Search: {pattern} ({cur}/{total} matches. {mode}{remain})", "搜索：{pattern}（第 {cur}/{total} 个匹配。{mode}{remain}）"),
    ("Search: {pattern} ({cur}/{total} matches. {mode})", "搜索：{pattern}（第 {cur}/{total} 个匹配。{mode}）"),
    (" searching {remain} lines", " 正在搜索剩余 {remain} 行"),
    ("case-sensitive", "区分大小写"),
    ("ignore-case", "忽略大小写"),
    ("smart-case", "智能大小写"),
    ("regex", "正则"),
    # ---- quick select ----
    (
        "Select: {input}  (type highlighted prefix to {action}, uppercase pastes, ESC to cancel)",
        "选择：{input}（输入高亮前缀即可{action}，大写前缀直接粘贴，ESC 取消）",
    ),
    ("copy", "复制"),
    # ---- launcher ----
    ("Launcher", "启动器"),
    ("Tab Navigator", "标签页导航器"),
    ("Select an item and press Enter=launch  Esc=cancel  /=filter", "选择条目后 Enter=启动  Esc=取消  /=过滤"),
    ("Fuzzy matching: ", "模糊匹配："),
    ("(default shell)", "（默认 shell）"),
    ("domain `{name}`", "域 `{name}`"),
    ("domain `{name}` - {label}", "域 `{name}` - {label}"),
    ("New Tab ({label})", "新建标签页（{label}）"),
    ("Attach {label}", "附加 {label}"),
    ("Switch to workspace: `{ws}`", "切换到工作区：`{ws}`"),
    ("Create new Workspace (current is `{ws}`)", "新建工作区（当前为 `{ws}`）"),
    ("Create new Workspace", "新建工作区"),
    ("{title}. {n} panes", "{title}。{n} 个窗格"),
    # ---- debug overlay ----
    ("Debug", "调试"),
    ("Debug Overlay", "调试浮层"),
    ("Enter lua statements or expressions and hit Enter.", "输入 Lua 语句或表达式后按回车。"),
    ("Press ESC or CTRL-D to exit", "按 ESC 或 CTRL-D 退出"),
    # ---- char select groups ----
    ("Recent", "最近使用"),
    ("Emotion", "表情"),
    ("People", "人物"),
    ("Animals", "动物"),
    ("Food", "食物"),
    ("Travel", "旅行"),
    ("Activities", "活动"),
    ("Objects", "物品"),
    ("Symbols", "符号"),
    ("Flags", "旗帜"),
    ("NerdFonts", "Nerd 字体"),
    ("Unicode", "Unicode"),
    ("Short Codes", "短代码"),
    # ---- config error / fatal toasts ----
    ("(this window will close automatically)", "（此窗口将自动关闭）"),
    ("Failed: {err}", "失败：{err}"),
    ("wezterm Configuration Error", "wezterm 配置错误"),
    ("Wezterm panic", "Wezterm 崩溃"),
    ("Wezterm Error", "Wezterm 错误"),
]


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    pairs = sorted(PAIRS, key=lambda p: p[0].encode("utf-8"))
    keys = [k for k, _ in pairs]
    assert len(keys) == len(set(keys)), "duplicate keys!"
    print("//! zh-CN 译表：按 key（英文原文）字典序排序，binary_search 查找。")
    print("//! 新增条目必须保持有序（`i18n::tests::zh_table_sorted_unique` 守门）；")
    print("//! 重建用 `python3 scripts/gen_zh_table.py`（见脚本内说明）。")
    print("//! 带参数的文案存 `{name}` 模板，取词后经 `i18n::fill` 填参。")
    print()
    print("use std::borrow::Cow;")
    print()
    print("pub(crate) static ZH_CN: &[(&str, &str)] = &[")
    for key, value in pairs:
        print(f'    ("{esc(key)}", "{esc(value)}"),')
    print("];")
    print()
    print("/// Look up `key` in the zh-CN table, falling back to the key itself")
    print("pub fn translate(key: &'static str) -> Cow<'static, str> {")
    print("    ZH_CN")
    print("        .binary_search_by(|(k, _)| (*k).cmp(key))")
    print("        .ok()")
    print("        .map(|idx| Cow::Borrowed(ZH_CN[idx].1))")
    print("        .unwrap_or(Cow::Borrowed(key))")
    print("}")


if __name__ == "__main__":
    main()
